apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: access
spec:
  rules:
    - host: neyothetechguy.com.ng
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: your-service
                port:
                  number: 80
