apiVersion: networking.k8s.io/v1
kind: ingress
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
    - host: prometheus.neyothetechguy.com.ng
      http:
        paths:
          - pathType: Prefix
            path: /
            backend: 
              service:
                name: prometheus
                port:
                  number: 443




apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: my-ingress
   namespace: sock-shop
   annotations:
     kubernetes.io/ingress.class: nginx
 spec:
   ingressClassName: nginx
   rules:
   - host: neyothetechguy.com.ng.com
     http:
       paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: front-end
             port:
               number: 80
       - path: /prometheus
         pathType: Prefix
         backend:
           service:
             name: prometheus-operated    
             port:
               number: 9090